### PR TITLE
Merge old Op3 device to new LineageOS

### PR DESCRIPTION
**Pull request by ZeNiXxX**

### CODE REVIEW

**Comment by ZeNiXxX** [comment]
merge op3 devices LineageOS

**Comment by ItzLevvie** [comment]
Hi there;

I'm writing this message to let you know that, LineageOS doesn't merge pull
requests submitted directly to their github.com repositories.

You can submit your change requests through their public review system,
located at http://review.lineageos.org/

That review system is an installation of Google's Gerrit code review.

Thanks!

**Comment by lineageos-gerrit** [comment]
Hi there;

This is an automated reply, to let you know LineageOS doesn't merge pull
requests submitted directly to our github.com repositories.

You can submit your change requests through our public review system,
located at https://review.lineageos.org/

That review system is an installation of Google's Gerrit code review.
If you've never interacted with Gerrit before, we also suggest you take
a look at https://zifnab.net/~zifnab/wiki_dump/Howto:_Gerrit.html

Thanks!

**Comment by ZeNiXxX** [comment]
how to remove my changes or commit ? it happened accidentally

**Pull request closed without merging**
